### ISSUE TITLE
Testing the plugin with Redmine 4.1.0

### ISSUE THREAD

**Issue by nanego** [synbioz/redspot-redmine-plugin#2]
Hello
I cannot wait to test this amazing plugin.
Unfortunately, I have some issues when I try to use it on my Redmine instance (using Redmine 4.1.0, without any other plugin).

I would like to help, but the errors I get are in the JavaScript part, and I am not an expert with VueJS. 

Do you know if the plugin is compatible with Redmine 4.1.0?
Do you currently use it in production?

Here are the errors that show up in my browser console:
<img width="645" alt="Capture d’écran 2020-03-28 à 21 49 57" src="https://user-images.githubusercontent.com/1620522/77833526-59fec000-713e-11ea-994f-5c7c6920ebe5.png">
<img width="646" alt="Capture d’écran 2020-03-28 à 21 50 16" src="https://user-images.githubusercontent.com/1620522/77833529-5ff4a100-713e-11ea-9bab-bb7e89416ae0.png">

Thank you for this impressive work!

**Comment by victordarras** [comment]
Sorry I did not tested with Redmine 4.1 but I just created a fix in the `feature/dockerize` branch, can you try and get back to me ?

**Comment by victordarras** [comment]
For information, the element requested by the plugin does not exist anymore in recent version of redmine.

And no, I don't use it anymore, we switched from Redmine to Gitlab.

**Comment by nanego** [comment]
Just tested the `feature/dockerize` branch. It works well with Redmine 4.1.0.
Thank you, Victor!

About the missing element... I don't see any error in my logs. Do you have some details about this issue?

**Comment by victordarras** [comment]
Nice I'll merge then.

Nevermind the error , it won't happen ;)

**Comment by nanego** [comment]
I've just seen your changes regarding the projects dropdown.
Great job! Thanks.

**Comment by victordarras** [comment]
Thx :) probably need a bit of refactoring... in the next days !
